config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :categories, only: [:new, :create, :show, :index]

  resources :articles do
    resources :comments
  end

  root 'welcome#front_page'
  get 'welcome', to: 'welcome#front_page', as: 'welcome'
  #Cover_letters
  get 'influitive', to: 'cover_letters#influitive', as: 'influitive'
  get 'info_tech', to: 'cover_letters#info_tech', as: 'info_tech'
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: {minimum: 2}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/api/articles_controller.rb
module Api
  class ArticlesController < ApplicationController
    def show
      article = Article.find(params[:id])

      render json: ::JSONAPI::Serializer.serialize(article)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # http_basic_authenticate_with name: ENV['NAME'], password: ENV['PASSWORD'] , except: [:index, :show]

  def new
    @article = Article.new
    @articles = Article.all
  end

  def create
    respond_to do |format|
      format.html do
        @article = Article.new(article_params)
        @articles = Article.all
        if @article.save
          redirect_to @article
        else
          render 'new'
        end
      end

      format.json  do
        @article = Article.new(article_params)
        @article.save
        render json: ::ArticleSerializer.serialize(@article)
      end
    end
  end

  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html {
        @articles = Article.all
        render :show
      }

      format.json {
        render json: ::ArticleSerializer.serialize(@article, include: ['comments', 'categories'])
      }
    end
  end

  def index
    @articles = Article.all.order('created_at DESC').paginate(page: params[:page])
    @categories = Category.all

    respond_to do |format|
      format.html
      format.json {
        render json: ArticleSerializer.serialize(@articles, is_collection: true)
      }
    end
  end

  def edit
    @article = Article.find(params[:id])
    @articles = Article.all
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @articles = Article.all
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
  def article_params
    params.require(:article).permit!
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # http_basic_authenticate_with name: ENV['NAME'], password: ENV['PASSWORD'], only: [:new, :create]
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      format.html {
        if @category.save
          redirect_to new_category_path
        else
          render :new
        end
      }

      format.json {
        @category.save
        render json: @category
      }
    end

  end

  def index
    render json: CategorySerializer.serialize(Category.all, is_collection: true)
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @articles = Category.find(params[:id]).articles.order('created_at DESC')
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
  before_action :find_article

  def create
    @comment = @article.comments.create(comment_params)

    respond_to do |format|
      format.html { redirect_to article_path(@article) }
      format.json { render json: ::CommentSerializer.serialize(@comment) }
    end
  end

  def index
    render json: ::CommentSerializer.serialize(@article.comments.reverse, is_collection: true)
  end

  def destroy
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

  def find_article
    @article = Article.find(params[:article_id])
  end
end

app/controllers/cover_letters_controller.rb
class CoverLettersController < ApplicationController
  def the_score; end
  def stack_builders; end
  def influitive; end
  def info_tech; end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def front_page
    @articles = Article.last(2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    include Redcarpet::Render::SmartyPants
    def block_code(code, language)
      Pygments.highlight(code, :lexer => language, :options => {:lineanchors => "line"})
    end
  end

  def markdown(text)
    renderer = HTMLwithPygments.new(prettify: true, hard_wrap: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_spacing: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true,
      highlight: true,
      quote: true,
      footnotes: true,
      tables: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_articles_header.html.erb
<header class="header">
  <div class="container">                       
    <div class='row articles-header-row'>
      <div class = 'col-sm-9'>
        <div class="profile-content pull-left">
          <h1 id="blog-name"> <span id = 'coffee'>Coffee</span> <span id = 'and'> & </span> <span id='tags-blog-header'>&lt;tags<span id='forwardslash'>&#47;</span>&gt;</span> </h1>
        </div><!--//profile-->
      </div> <!-- end of column 5  -->
     <div class = 'col-sm-3'>
       <%= link_to welcome_path do %>
         <button class = 'btn btn-cta-primary pull-right'>
             <i class="fa fa-home"></i>Home
         </button>
       <%end%>
     </div>
    </div> <!-- end of row -->
  </div><!--//container-->
</header><!--//header-->

app/views/articles/_discus.html.erb
<div id="disqus_thread"></div>
  <script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'eduardoblog'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/articles/_form.html.erb
<%= bootstrap_form_for(@article) do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :text, rows: 10 %>
  <%= f.form_group :categories do %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, label: "Choose Category"%>
  <%end%>
  <%= f.submit "Post!" %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= render 'articles/articles_header' %>
<%= render partial: "shared/articles", locals: {articles: @articles} %>
<%= will_paginate @articles, renderer: BootstrapPagination::Rails %>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<div class="blog-post">
	<h1 class="blog-post-title-showpage text-center"><%= raw @article.title %></h1>
  <p class="blog-post-meta text-center">  <i>by Eduado Poleo at <%= @article.created_at.strftime("%b %d, %Y") %></i></p>
  <div class ='badges-container text-center'>
    <% @article.categories.each do |cat| %>
      <span class='badge'><%=link_to cat.name, category_path(cat) %></span>
    <% end %>
  </div>
  <p class='text-center'> <%=link_to '...back to articles', articles_path %> </p>
  <p><%= markdown @article.text %> </p>
</div><!-- /.blog-post -->

<%= link_to "Back to Articles...", articles_path%> 
 
<%= render "comments/disqus" %>

app/views/categories/_categories_header.html.erb
<h1 id='big-category-name' class='text-center'><%=category.name%></h1>
<div  id='back-to-blog' class='text-center'>
  <a  href='http://epoleo.me/articles'>..back to blog</a>
</div>

app/views/categories/new.html.erb
<div class = "container">
  <h1 class = 'text-center'>Create a category!</h1>
  <%= bootstrap_form_for(@category) do |f| %>
    <%= f.text_field :name %>
    <%= f.submit "Create" %>
  <% end %>
</div>

app/views/categories/show.html.erb
<%= render partial: "categories_header", locals: {category: @category} %>
<%= render partial: "shared/articles", locals: {articles: @articles} %>

app/views/comments/_comment.html.erb
<div class="comment-bubble">


	
	<h3 class="commenter"><%= comment.commenter %></h3>
	
	<p class="comment-text"><%= simple_format(comment.body)%></p>
			 
	
</div>
<br>

app/views/comments/_disqus.html.erb
<div id="disqus_thread"></div>
  <script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'eduardoblog'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :Name %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :Comment %><br>
    <%= f.text_area :body ,size: "66x6"%>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/cover_letters/influitive.html.erb
<div class = 'row text-center header-influitive'>
  <h1 id ='salutation'>
    <span id='hi-influitive'>Dear</span> <span id='influitive'> Influitive, </span> 
  </h1>
</div>

<div class ='influitive-content'>
  <p>My name is Eduardo Poleo and I am a chemical engineer who codes. I have been coding in Ruby/Rails for about a year now and I think I am ready to join your awesome development team to learn and expand my abilities. After going through some of your blog entries I was entirely convinced that I wanted to join your team because:</p>

  <div class="row" id='qualities-row'>
    <div class="col-xs-4 text-center">
      <h2 class = 'influitive-quality'><a class='influitive-link' href = 'http://influitive.com/blog/how-game-of-thrones-helped-us-take-over-marketo-summit/'>You're unconventional </i></a></h2>
      <a href = 'http://influitive.com/blog/how-game-of-thrones-helped-us-take-over-marketo-summit/'>
        <%= image_tag('unconventional.png', class: 'text-center circular-image') %>
      </a>
      <p class = 'quality-description'>By leveraging the current cultural context and taking an unconventional approach you outplay other rigid, ‘by the book’ corporations.</p>
    </div>

    <div class="col-xs-4 text-center">
      <h2 class = 'influitive-quality'> <a class='influitive-link' href='http://influitive.com/blog/5-things-programmer-developer-advocates-crave/'>You understand us</a></h2>
      <a href = 'http://influitive.com/blog/5-things-programmer-developer-advocates-crave/'>
        <%= image_tag('geek.png', class: 'text-center circular-image') %>
      </a>
      <p class = 'quality-description'>You show a deep understanding of developers craft and motivation. I wished other people in the past had understood this before deciding to approach me. </p>
    </div>

    <div class="col-xs-4 text-center">
      <h2 class = 'influitive-quality'> <a class = 'influitive-link' href = 'http://influitive.com/blog/study-advocate-marketing-helps-brands-get-17-5x-more-reviews-than-average/'>You innovate </a></h2>
      <a href = 'http://influitive.com/blog/study-advocate-marketing-helps-brands-get-17-5x-more-reviews-than-average/'>
        <%= image_tag('idea.png', class: 'text-center circular-image') %>
      </a>
      <p class = 'quality-description'> Your advocacy-driven approach to business growth allows for more unbiased, effective and trustful brand marketing. </p>
    </div>
  </div> 
  <h1 class = 'text-center' id='contribution-intro'>...and this is how I can contribute to the team</h1>
</div>

  <table class = "table text-center" id='influitive-table'  >
    <tr class = "odd-row-influitive" id='header-row-influitive'>
      <th class ="text-center" width="40">Skills</th>
      <th class ="text-center" width="60">Things I do</th>
    </tr>

    <tr class = "even-row-influitive" >
      <td>Ruby and RoR</td>
      <td>
        <ul>
          <li>Use rails to create <a href='/'>applications</a> with diverse level of complexity.</li>
          <li>Use ruby to solve <a href='/articles/26'>programming challenges</a>.</li>
        </ul>
      </td>
    </tr>

    <tr class = "odd-row-influitive">
      <td>Sidekiq and background processes</td>
      <td><a href='/articles/31'>Integrate Sidekiq/Redis</a> with third party services to avoid possible UX disruption.</td>
    </tr>

    <tr class = "even-row-influitive">
      <td>Amazon S3 and Carrierwave</td>
      <td><a href='/articles/40'>Integrated Carrierwave and Amazon S3</a> for image and file upload to the ‘cloud’.</td>
    </tr>

    <tr class = "odd-row-influitive">
      <td>TDD</td> 
      <td>
        <ul>
          <li>Used TDD to implement not trivial <a href= '/articles/28'>business work-flows</a>.</li>
          <li>Used TDD for the crafting of<a href='/articles/36'> complex ruby algorithms</a>.</li>
        </ul>
      </td> 
    </tr>

    <tr class = "even-row-influitive">
      <td>Passion</td>
      <td>
        <ul>
          <li>Keep a ‘hand made’ and up to date <a href='/articles'>blog</a> with entries of diverse technologies.</li>
          <li>Religiously join the <a href='/categories/11'>ruby hack-nights</a> and collaborate with ideas and create original solutions to the work-shop problems.</li>
          <li>Help fellow developers to the best of my abilities.</li>
        </ul>
      </td>
    </tr>
  </table>

<div class = 'sb-content'>
  <p>Lastly, I am committed to become the best developer I can be, and I am constantly learning and creating new things. I also believe in the work-hard/play-hard motto and I like to spend my free time running, playing board games (I own a collection of 17 different games) and watching movies. If you want to know more about me please make sure to check my <a class='influitive-link' href='/Resume.pdf'> resume </a> and my <a class='influitive-link' href='/'>portfolio site</a>. I hope to hear back from you soon.</p>

  <p>Eduardo Poleo</p>
</div>

app/views/cover_letters/info_tech.html.erb
<div class = 'row text-center header-info-tech'>
  <h1 id ='salutation-info-tech'>
    <span id='hi-info-teck'>Dear</span> <span id='info-tech'> Info~Tech,</span> 
  </h1>
</div>

<div class ='info-tech-content'>
  <p> My name is Eduardo Poleo and I am a chemical engineer who codes. I have been coding in Ruby/Rails for about a year now and I think I am ready to join your awesome development team to learn and expand my abilities. After going through some of your case-studies I was entirely convinced that I wanted to join your team because: </p>
</div>

<div class="row" id='qualities-info-tech'>
  <div class="col-xs-4 text-center quality-box">
    <a class='full-box-link' href='http://d1prilht7d22jo.cloudfront.net/downloads/ITRG-MasterBrand-Cabinets-Case-Study.pdf'>
      <div class='inner-box-1'>
        <h4 class = 'info-tech-quality-name'>You know the tech market</h4>
        <hr class ='info-tech-divisor'>
        <p class = 'info-tech-quality'>You are constantly analyzing the pros and cons of different technologies and vendors in order to understand the different trade-offs implicated.</p>
      </div>
    </a>
  </div>

  <div class="col-xs-4 text-center quality-box">
    <a class='full-box-link' href='http://d1prilht7d22jo.cloudfront.net/downloads/ITRG-CCR-Case-Study.pdf'>
      <div class='inner-box-2'>
        <h4 class = 'info-tech-quality-name'>You care about your clients</h4>
        <hr class ='info-tech-divisor'>
        <p class = 'info-tech-quality'>You provide highly customized solutions and insights to your clients, and make sure to cover every possible angle involved in the challenge at hand.</p>
      </div>
    </a>
  </div>

  <div class="col-xs-4 text-center quality-box">
    <a href= 'http://d1prilht7d22jo.cloudfront.net/downloads/ITRG-Boston-Pizza-Case-Study.pdf' class='full-box-link'>
      <div class='inner-box-3'>
        <h4 class = 'info-tech-quality-name'> Your work matters</h4>
        <hr class ='info-tech-divisor'>
        <p class = 'info-tech-quality'>By helping and being recognized by high profile companies you ensure that your work is impactful and affects millions of people.</p>
      </div>
    </a>
  </div>
</div> 

<h1 class = 'text-center' id='contribution-intro'>...and this is how I can contribute to the team</h1>

<table class = "table text-center" id='info-tech-table'  >
  <tr class = "odd-row-info-tech text-center" id='header-row-info-tech'>
    <th class ="text-center" width="40">What you are looking for</th>
    <th class ="text-center" width="60">Things I do</th>
  </tr>

  <tr class = "even-row-info-tech" >
    <td>Some exposure working with Ruby on Rails.</td>
    <td>
      <ul>
        <li>Use rails to create <a class = 'info-tech-link' href='/'>applications</a> with diverse level of complexity.</li>
        <li>Use <a class = 'info-tech-link' href = '/articles/24'>TDD</a> and best practices to develop production quality applications.</li>
      </ul>
    </td>
  </tr>

  <tr class = "odd-row-info-tech">
    <td>Solid understanding of web technologies, relational databases (we use MySQL), and object oriented design.</td>
    <td>
      <ul>
        <li>Create information systems that employ non-trivial <a class = 'info-tech-link' href='/articles/28'>business workflows</a> and <a class ='info-tech-link' href='/articles/15'>model associations</a>.</li>
        <li>Craft <a href='/articles/36' class='info-tech-link'>ruby algorithms</a> employing object oriented patterns and different data structures.</li>
      </ul>
    
    </td>
  </tr>

  <tr class = "even-row-info-tech">
    <td>Experience with Ajax based user interfaces.</td>
    <td>Enhance user experience by implementing <a class='info-tech-link' href = '/articles/16'>asynchronous server responses</a>.</td>
  </tr>

  <tr class = "odd-row-info-tech">
    <td>Comfortable working with HTML5, CSS3, SCSS, CoffeeScript, JavaScript, jQuery.</td> 
    <td>
      <ul>
        <li>Create intuitive web layouts to communicate ideas and content effectively.</li>
        <li>Use different <a class = 'info-tech-link' href = '/articles/16'>JQuery use cases and libraries </a> to enhance site interactivity.</li>
      </ul>
    </td> 
  </tr>

  <tr class = "even-row-info-tech">
    <td>
      <ul>
        <li>Have great work ethics and attention to detail.</li>
        <li>Have great analytical skills and communicate well.</li>
      </ul>
    </td>
    <td>
      Published two journal papers that required thorough calculations and sharp analysis of large amount of data:
      <ul>
        <li><a class ='info-tech-link' href='http://sciencedirect.com/science/article/pii/S0304389413002161'> J. Hazard. Mater., 254-255: 206-213 (2013)</a></li>
        <li> <a class = 'info-tech-link' href='http://onlinelibrary.wiley.com/doi/10.1002/jctb.4116/abstract'> J. Chem. Technol. Biotechnol., 89: 88-96 (2014)</a></li>
      </ul>
    </td>
  </tr>
</table>

<div class = 'info-tech-content'>
  <p>Lastly, I am really passionate for what I do. I keep a ‘hand made’ and up to date <a class = 'info-tech-link' href = '/articles'>blog</a> where I write about ruby and web development . I also religiously join the <a class ='info-tech-link' href='http://www.meetup.com/torontoruby/'>ruby hack-nights</a> to collaborate and provide <a class = 'info-tech-link' href='/categories/11'>original solutions</a> to coding challenges. If you want to know more about me or my work please make sure to check my <a class='info-tech-link' href= 'Resume.pdf'>resume</a>, <a class ='info-tech-link' href='https://github.com/eduardopoleo'>github profile</a> and my <a class= 'info-tech-link' href ='/'>portfolio site</a>. I hope to hear back from you soon.</p>

  <p id='eduardo-poleo'>Eduardo Poleo</p>
</div>

app/views/cover_letters/stack_builders.html.erb
<div class = 'row text-center'>
  <h1>
    <span id='hi-sb'>Hi,</span> <%=image_tag("stack_builder.png")%> 
  </h1>
</div>

<div class ='sb-content'>
  <p>My name is Eduardo Poleo and I am chemical engineer who codes. I have been working with ruby/rails for about a year now and I want to join your great development team. I really appreciate how you leverage team <a class = 'sb-link' href="http://www.stackbuilders.com/news/i-m-making-a-list-and-checking-it-twice" target="_blank">organization</a> and <a class = 'sb-link' href='http://www.stackbuilders.com/news/software-development-runs-on-trust'> trust</a>, and I am thrilled with the possibility of adding functional programming to my arsenal, given its <a class='sb-link' href = 'http://www.stackbuilders.com/news/can-haskell-power-the-next-ruby-on-rails'>continuous rise</a> on the web scenario. </p>

  <p>The table below contains urls to code samples I have written. Sample A corresponds to my solution to an exercise presented in one of the <a class ='sb-link' href ='http://www.meetup.com/torontoruby/events/219693482/'>ruby hack-nights</a> hosted here in Toronto. Sample B is a wrapper I coded for an <a class ='sb-link' href = "http://firecamp.herokuapp.com/">e-commerce application</a>.</p>
</div>

  <table class = "table text-center" id='sb-table'  >
    <tr class = "odd-row-sb" id='header-row-sb'>
      <th class ="text-center" width="10"></th>
      <th class ="text-center" width="40">Code Sample A: String-kata</th>
      <th class ="text-center" width="40">Code Sample B: Stripe Wrapper</th>
    </tr>

    <tr class = "even-row-sb" >
      <td> Relevant Technology </td>
      <td> Ruby/Rspec </td>
      <td> Rails/Rspec </td>
    </tr>

    <tr class = "odd-row-sb">
      <td>Description</td>
      <td>A calculator program that takes a string as input. The challenge of the problem relied on the irregularity of the string, which gradually increased with every requirement.</td>
      <td>Fully tested api wrapper for the integration of Stripe payment handling into a RoR application.</td>
    </tr>

    <tr class = "even-row-sb">
      <td>Relevant links</td>
      <td>
     <ul class = 'list-sb'>
       <li> <a class='sb-link-inside-table' href = 'https://github.com/eduardopoleo/string-kata/blob/master/lib/string_calculator.rb'>Working code </a> </li>
       <li> <a class='sb-link-inside-table' href = 'https://github.com/eduardopoleo/string-kata/blob/master/spec/string_calculator_spec.rb'>Test Suite</a></li>
       <li> <a class='sb-link-inside-table' href = 'http://www.epoleo.me/articles/26'>Blog post </a></li>
     </ul> 
      </td>
      <td>
      <ul class = 'list-sb'>
       <li> <a class = 'sb-link-inside-table' href = 'https://github.com/eduardopoleo/firecamp/blob/master/app/models/stripe_wrapper.rb'>Working code </a> </li>
       <li> <a class = 'sb-link-inside-table' href = 'https://github.com/eduardopoleo/firecamp/blob/master/spec/models/stripe_wrapper_spec.rb'>Test Suite</a></li>
       <li> <a class = 'sb-link-inside-table' href = 'http://www.epoleo.me/articles/33'>Blog post </a></li>
     </ul>
      </td>
    </tr>
  </table>

<div class = 'sb-content'>
  <p>Lastly I am currently located in Toronto, Canada and I speak Spanish fluently being born and raised in Venezuela. If you want to know more about me please make sure to check my <a class = 'sb-link' href ='/Resume.pdf'>resume</a> and my <a class = 'sb-link' href = '/'> portfolio</a> page.  Thank you very much for your time and I hope to hear back from you soon.</p>

  <p>Eduardo Poleo</p>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container text-center">
    <small class="copyright">Eduardo Poleo @2015</small> <br>
    <a class="social-media" href="https://ca.linkedin.com/pub/eduardo-poleo/56/364/a4">
      <span class="fa-stack">
        <i class="fa fa&#45;linkedin"></i>
      </span>
    </a>
    <a class="social-media" href="https://github.com/eduardopoleo">
      <span class="fa-stack">
        <i class="fa fa&#45;github"></i>
      </span>
    </a>
  </div><!--//container-->
</footer><!--//footer-->

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/header' %>
  <body>
    <%=yield%>
  </body>
</html>

app/views/shared/_articles.html.erb
<div class = 'row'>
  <div class = 'col-sm-8 col-xs-12 blog-mail'>
    <% articles.each do |article| %>
      <div class="blog-post">
        <% article.categories.each do |cat| %>
          <span class='badge'><%=link_to cat.name, category_path(cat) %></span>
        <% end %>
        <%=link_to article_path(article), {:class =>"link_to-style"} do %>
           <h2 class="blog-post-title"><%= raw article.title %></h2>
        <% end %>
        <p class="blog-post-meta">  <i><%=article.created_at.strftime("%b %d, %Y") %></i></p>
        <p><%= markdown article.text.slice(0..400) %> ... <%= link_to 'Show more', article_path(article) %></p>
      </div><!-- /.blog-post -->	
    <% end %> 
  </div>
  <div class = 'col-sm-3 col-sm-offset-1 col-xs-12 blog-sidebar'>
    <%= render 'shared/blog_sidebar' %> 
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="sidebar-module sidebar-module-inset">
  <h2 class= "heading">Categories</h2>
  <ul id='category-list'> 
    <% @categories.each do |cat| %>
      <li>
        <i class="fa fa-caret-right"></i>
        <%= link_to category_path(cat) do %>
          <%= "#{cat.name} (#{cat.articles.size})" %> 
        <% end %>
      </li>
    <%end%>
  </ul>

</div>

<div class="sidebar-module sidebar-module-inset">
  <h2 class= "heading">Latest Posts</h2>
  <ol class="list-unstyled">
    <%@articles.first(2).each do |article| %>
      <%=link_to article_path(article), {:class=>"link_to-style"} do %>
      <li class = "side-list"><%=article.title%></li>
      <% end %>
      <p class="side-list-date"><%= article.created_at.strftime("%b %d, %Y") %></p>
      <br>
    <%end%>
  </ol>
</div>